title:              Chaelin's Blog
email:              cofls749@naver.com
description:        공유와 기록을 위한 공간
author:             ChaelinJ
baseurl:            ""
url:                "https://chaelin1211.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    chaelin1211
# facebook_username:  StartBootstrap
# instagram_username:  
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code
# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  