algorithm : Algorithm
baekjoon : 백준알고리즘
githubBlog: Github블로그
jekyll: jekyll
rest: REST
restful: RESTful
miniproject: Mini Project
error: Error
todolist: TO-DO List
spring: Spring 
lombok: Lombok
markdown: MarkDown
database: Database
mongodb: mongoDB
reactjs: React.js
nodejs: Node.js
docker: Docker
designpattern: Design Pattern
opensource: OpenSource
openapi: Open API
hibernate: Hibernate
thymeleaf: Thymeleaf
ajax: Ajax
javascript: JavaScript
java: Java
network: Network
interview: 실무면접
os: OS
library: Library
swagger: Swagger
authentication: 인증
til: TIL
mybatis: myBatis
ruby: Ruby
jpa: JPA
css: CSS
vuejs: Vue.js
nuxtjs: Nuxt.js
yarn: Yarn
linux: Linux
web: Web
