import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/src/app/nav-bar";
import Link from "next/link";
import React from "react";
import Footer from "@/src/app/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chaelin's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>
          <Link href="/">Chaelin&apos;s Blog (Temp)</Link>
        </h1>
        <NavBar />

        {children}

        <Footer />
      </body>
    </html>
  );
}
