import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/src/app/ui/layout/nav-bar";
import React from "react";
import Footer from "@/src/app/ui/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chaelin's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NavBar />
        <div className="post-main mx-auto max-w-7xl">
          <div className="px-6 py-10">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
